version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "macros"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
