# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html

targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-apple-darwin" },
    { triple = "wasm32-unknown-unknown" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
notice = "deny"
unmaintained = "deny"
vulnerability = "deny"
yanked = "deny"

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "deny"
wildcards = "deny"

[licenses]
allow = [
  "Apache-2.0",
  # "BSD-2-Clause",
  # "BSD-3-Clause",
  # "CC0-1.0",
  # "ISC",
  # "LicenseRef-ring",
  "MIT",
  # "MPL-2.0",
  "Unicode-DFS-2016",
  # "Zlib",
]
confidence-threshold = 0.8
copyleft = "deny"
unlicensed = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
